# -*- coding: utf-8 -*-
"""FinalProject_1301204135_1301204028.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-X2EunwCbrc7NNes2E6nYe7_blLZ5T_5
"""

import pandas as pd
from bokeh.io import curdoc
from bokeh.plotting import figure
from bokeh.models import HoverTool, ColumnDataSource
from bokeh.models import CategoricalColorMapper
from bokeh.palettes import Spectral6
from bokeh.layouts import widgetbox, row, gridplot
from bokeh.models import Slider, Select

data = pd.read_csv("https://raw.githubusercontent.com/galihatha/Visdat/main/data-penumpang-bus-transjakarta-januari-desember-2021.csv")
# Set the index to 'bulan'
data.set_index('bulan', inplace=True)

# Remove rows with NaN values in 'jenis' column
data = data.dropna(subset=['jenis'])

# Convert 'jenis' column to string
data['jenis'] = data['jenis'].astype(str)

# Make a color mapper: color_mapper
color_mapper = CategoricalColorMapper(factors=data['jenis'].unique().tolist(), palette=Spectral6)

# Make the ColumnDataSource: source
source = ColumnDataSource(data={
    'x': data['jenis'],
    'y': data['kode_trayek'],
    'trayek': data['trayek'],
    'jumlah_penumpang': data['jumlah_penumpang']
})

# Create the figure: plot
plot = figure(title='Data Penumpang Bus TransJakarta', x_axis_label='Jenis', y_axis_label='Kode Trayek',
              plot_height=400, plot_width=700, tools=[HoverTool(tooltips='@trayek')])

# Add a circle glyph to the figure
plot.circle(x='x', y='y', source=source, fill_alpha=0.8,
            color=dict(field='x', transform=color_mapper), legend='jenis')

# Set the legend and axis attributes
plot.legend.location = 'bottom_left'

# Define the callback function: update_plot
def update_plot(attr, old, new):
    # set the `month` name to `slider.value` and `source.data = new_data`
    month = slider.value
    x = x_select.value
    y = y_select.value
    # Label axes of plot
    plot.xaxis.axis_label = x
    plot.yaxis.axis_label = y
    # new data
    new_data = {
        'x': data[data['bulan'] == month][x],
        'y': data[data['bulan'] == month][y],
        'trayek': data[data['bulan'] == month]['trayek'],
        'jumlah_penumpang': data[data['bulan'] == month]['jumlah_penumpang']
    }
    source.data = new_data
    
    # Add title to figure: plot.title.text
    plot.title.text = 'Data Penumpang Bus TransJakarta - Bulan %s' % month

# Make a slider object: slider
slider = Slider(start=1, end=12, step=1, value=1, title='Bulan')
slider.on_change('value', update_plot)

# Make dropdown menu for x and y axis
# Create a dropdown Select widget for the x data: x_select
x_select = Select(
    options=['jenis', 'kode_trayek', 'trayek', 'jumlah_penumpang'],
    value='jenis',
    title='x-axis data'
)

# Attach the update_plot callback to the 'value' property of x_select
x_select.on_change('value', update_plot)

# Create a dropdown Select widget for the y data: y_select
y_select = Select(
    options=['jenis', 'kode_trayek', 'trayek', 'jumlah_penumpang'],
    value='kode_trayek',
    title='y-axis data'
)
# Attach the update_plot callback to the 'value' property of y_select
y_select.on_change('value', update_plot)
    
# Create layout and add to current document
layout = row(widgetbox(slider, x_select, y_select), plot)
curdoc().add_root(layout)

from bokeh.io import save
save(layout)